"""Property-based tests for Logger class using Hypothesis.

This module contains property tests that validate universal correctness
properties of the logging system across a wide range of inputs.
"""

import json
import logging
import sys
from io import StringIO
from hypothesis import given, strategies as st, settings, HealthCheck
from src.logger import Logger, CorrelationContext


def capture_log_output(func):
    """Context manager to capture log output without using pytest fixtures."""
    old_stdout = sys.stdout
    sys.stdout = StringIO()
    try:
        func()
        output = sys.stdout.getvalue()
        return output
    finally:
        sys.stdout = old_stdout


# Property 33: Structured Logging Format
# Validates: Requirements 17.1, 17.2, 17.3
@settings(max_examples=100)
@given(
    component_name=st.text(min_size=1, max_size=50, alphabet=st.characters(
        whitelist_categories=('Lu', 'Ll', 'Nd'),
        whitelist_characters='_-'
    )),
    log_level=st.sampled_from(['DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL']),
    message=st.text(min_size=1, max_size=200),
    context_keys=st.lists(
        st.text(min_size=1, max_size=20, alphabet=st.characters(
            whitelist_categories=('Lu', 'Ll', 'Nd'),
            whitelist_characters='_'
        )),
        min_size=0,
        max_size=5,
        unique=True
    ),
    context_values=st.lists(
        st.one_of(
            st.integers(),
            st.floats(allow_nan=False, allow_infinity=False),
            st.text(max_size=50),
            st.booleans()
        ),
        min_size=0,
        max_size=5
    ),
    use_correlation_id=st.booleans(),
    correlation_id=st.text(min_size=1, max_size=50, alphabet=st.characters(
        whitelist_categories=('Lu', 'Ll', 'Nd'),
        whitelist_characters='-_'
    ))
)
def test_property_structured_logging_format(
    component_name,
    log_level,
    message,
    context_keys,
    context_values,
    use_correlation_id,
    correlation_id
):
    """
    Property 33: Structured Logging Format
    
    For ANY log entry generated by the Logger class, the output SHALL:
    1. Be valid JSON
    2. Contain required fields: timestamp, level, component, message
    3. Include correlation_id when set
    4. Include context when provided
    5. Have timestamp in ISO 8601 format
    6. Have level matching one of: DEBUG, INFO, WARNING, ERROR, CRITICAL
    
    This property validates Requirements 17.1, 17.2, 17.3:
    - 17.1: Structured JSON logging format
    - 17.2: Log level included in each entry
    - 17.3: Timestamp, component name, and correlation_id in logs
    """
    # Clear any existing correlation context
    CorrelationContext.clear()
    
    def log_action():
        # Create logger with specified component and level
        logger = Logger(component_name, log_level)
        
        # Set correlation ID if requested
        if use_correlation_id:
            logger.set_correlation_id(correlation_id)
        
        # Build context dictionary from keys and values
        context = {}
        for i, key in enumerate(context_keys):
            if i < len(context_values):
                context[key] = context_values[i]
        
        # Log message with context
        log_method = getattr(logger, log_level.lower())
        log_method(message, **context)
    
    # Capture output
    output = capture_log_output(log_action).strip()
    
    # Property 1: Output must be valid JSON
    try:
        log_data = json.loads(output)
    except json.JSONDecodeError as e:
        raise AssertionError(f"Log output is not valid JSON: {output}") from e
    
    # Property 2: Must be a dictionary
    assert isinstance(log_data, dict), f"Log output must be a dict, got {type(log_data)}"
    
    # Property 3: Required fields must be present
    required_fields = ['timestamp', 'level', 'component', 'message']
    for field in required_fields:
        assert field in log_data, f"Required field '{field}' missing from log output"
    
    # Property 4: Field values must match expected types
    assert isinstance(log_data['timestamp'], str), "timestamp must be a string"
    assert isinstance(log_data['level'], str), "level must be a string"
    assert isinstance(log_data['component'], str), "component must be a string"
    assert isinstance(log_data['message'], str), "message must be a string"
    
    # Property 5: Level must match the log level used
    assert log_data['level'] == log_level, f"Level mismatch: expected {log_level}, got {log_data['level']}"
    
    # Property 6: Component must match the logger's component
    assert log_data['component'] == component_name, f"Component mismatch: expected {component_name}, got {log_data['component']}"
    
    # Property 7: Message must match the logged message
    assert log_data['message'] == message, f"Message mismatch: expected {message}, got {log_data['message']}"
    
    # Property 8: Timestamp must be in ISO 8601 format
    timestamp = log_data['timestamp']
    assert 'T' in timestamp, "Timestamp must contain 'T' separator (ISO 8601)"
    assert timestamp.endswith('Z') or '+' in timestamp or ('-' in timestamp and timestamp.count('-') >= 2), \
        "Timestamp must have timezone indicator (ISO 8601)"
    
    # Property 9: Correlation ID must be present when set
    if use_correlation_id:
        assert 'correlation_id' in log_data, "correlation_id must be present when set"
        assert log_data['correlation_id'] == correlation_id, \
            f"Correlation ID mismatch: expected {correlation_id}, got {log_data['correlation_id']}"
    
    # Property 10: Context must be present when provided
    context = {}
    for i, key in enumerate(context_keys):
        if i < len(context_values):
            context[key] = context_values[i]
    
    if context:
        assert 'context' in log_data, "context must be present when provided"
        assert isinstance(log_data['context'], dict), "context must be a dictionary"
        # Verify all context keys are present
        for key in context_keys[:len(context_values)]:
            assert key in log_data['context'], f"Context key '{key}' missing from log output"
    
    # Property 11: No correlation_id field when not set
    if not use_correlation_id:
        assert 'correlation_id' not in log_data, "correlation_id should not be present when not set"
    
    # Property 12: No context field when not provided
    if not context:
        assert 'context' not in log_data, "context should not be present when not provided"


# Property: Correlation ID Propagation via Context
@settings(max_examples=100)
@given(
    correlation_id=st.text(min_size=1, max_size=50, alphabet=st.characters(
        whitelist_categories=('Lu', 'Ll', 'Nd'),
        whitelist_characters='-_'
    )),
    num_log_calls=st.integers(min_value=1, max_value=10)
)
def test_property_correlation_id_propagation(correlation_id, num_log_calls):
    """
    Property: Correlation ID Propagation
    
    For ANY correlation ID set via CorrelationContext, ALL subsequent log calls
    within the same thread SHALL include that correlation ID until it is cleared.
    
    This validates Requirement 17.3: correlation_id propagation through all log calls.
    """
    # Clear any existing correlation context
    CorrelationContext.clear()
    
    def log_action():
        # Create logger
        logger = Logger("TestComponent", "INFO")
        
        # Set correlation ID via context
        CorrelationContext.set(correlation_id)
        
        # Make multiple log calls
        for i in range(num_log_calls):
            logger.info(f"Message {i}")
    
    # Capture output
    output = capture_log_output(log_action).strip()
    output_lines = output.split('\n')
    
    # Property: All log entries must have the same correlation ID
    assert len(output_lines) == num_log_calls, \
        f"Expected {num_log_calls} log entries, got {len(output_lines)}"
    
    for i, line in enumerate(output_lines):
        log_data = json.loads(line)
        assert 'correlation_id' in log_data, f"Log entry {i} missing correlation_id"
        assert log_data['correlation_id'] == correlation_id, \
            f"Log entry {i} has wrong correlation_id: expected {correlation_id}, got {log_data['correlation_id']}"
    
    # Clean up
    CorrelationContext.clear()


# Property: Log Level Filtering
@settings(max_examples=100)
@given(
    configured_level=st.sampled_from(['DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL']),
    log_calls=st.lists(
        st.sampled_from(['DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL']),
        min_size=1,
        max_size=10
    )
)
def test_property_log_level_filtering(configured_level, log_calls):
    """
    Property: Log Level Filtering
    
    For ANY configured log level, ONLY log calls at that level or higher SHALL
    produce output. Log calls below the configured level SHALL be filtered out.
    
    This validates proper log level filtering behavior.
    """
    # Define level hierarchy
    level_hierarchy = {
        'DEBUG': 0,
        'INFO': 1,
        'WARNING': 2,
        'ERROR': 3,
        'CRITICAL': 4
    }
    
    def log_action():
        # Create logger with configured level
        logger = Logger("TestComponent", configured_level)
        
        # Make log calls at various levels
        for i, level in enumerate(log_calls):
            log_method = getattr(logger, level.lower())
            log_method(f"Message {i} at {level}")
    
    # Capture output
    output = capture_log_output(log_action).strip()
    output_lines = [line for line in output.split('\n') if line]
    
    # Property: Only logs at or above configured level should appear
    expected_count = sum(
        1 for level in log_calls
        if level_hierarchy[level] >= level_hierarchy[configured_level]
    )
    
    assert len(output_lines) == expected_count, \
        f"Expected {expected_count} log entries, got {len(output_lines)}"
    
    # Verify each output line is at or above configured level
    for line in output_lines:
        log_data = json.loads(line)
        log_level = log_data['level']
        assert level_hierarchy[log_level] >= level_hierarchy[configured_level], \
            f"Log entry at {log_level} should not appear with configured level {configured_level}"


# Property: Context Data Preservation
@settings(max_examples=100)
@given(
    context_data=st.dictionaries(
        keys=st.text(min_size=1, max_size=20, alphabet=st.characters(
            whitelist_categories=('Lu', 'Ll', 'Nd'),
            whitelist_characters='_'
        )).filter(lambda k: k not in ['level', 'message', 'args', 'kwargs']),  # Exclude reserved keywords
        values=st.one_of(
            st.integers(),
            st.floats(allow_nan=False, allow_infinity=False),
            st.text(max_size=50),
            st.booleans()
        ),
        min_size=1,
        max_size=10
    )
)
def test_property_context_data_preservation(context_data):
    """
    Property: Context Data Preservation
    
    For ANY context data provided to a log call, ALL key-value pairs SHALL
    be preserved exactly in the log output's context field.
    
    This validates that context data is not lost or corrupted during logging.
    
    Note: Context keys that conflict with Python reserved keywords or logging
    internals (level, message, args, kwargs) are excluded from testing.
    """
    def log_action():
        # Create logger
        logger = Logger("TestComponent", "INFO")
        
        # Log with context data
        logger.info("Test message", **context_data)
    
    # Capture output
    output = capture_log_output(log_action).strip()
    log_data = json.loads(output)
    
    # Property: Context field must be present
    assert 'context' in log_data, "Context field must be present when context data provided"
    
    # Property: All context keys must be present
    for key in context_data:
        assert key in log_data['context'], f"Context key '{key}' missing from log output"
    
    # Property: All context values must match exactly
    for key, value in context_data.items():
        assert log_data['context'][key] == value, \
            f"Context value mismatch for key '{key}': expected {value}, got {log_data['context'][key]}"
    
    # Property: No extra keys should be present
    assert set(log_data['context'].keys()) == set(context_data.keys()), \
        "Context should contain exactly the provided keys, no more, no less"
