"""Core data models for Store Intelligence Platform.

This module defines the fundamental data structures used throughout the system
for representing video frames, detections, tracks, zones, and events.
"""

from dataclasses import dataclass
from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Tuple

import numpy as np


@dataclass
class Frame:
    """Represents a single video frame with metadata.
    
    Attributes:
        frame_number: Sequential frame number (0-indexed)
        timestamp: Time in seconds from video start
        image: Frame image data in HxWx3 BGR format (OpenCV format)
        resolution: Frame dimensions as (width, height) tuple
    """
    frame_number: int
    timestamp: float
    image: np.ndarray
    resolution: Tuple[int, int]


@dataclass
class BoundingBox:
    """Represents a rectangular bounding box.
    
    Attributes:
        x: X-coordinate of top-left corner (pixels)
        y: Y-coordinate of top-left corner (pixels)
        width: Box width (pixels)
        height: Box height (pixels)
    """
    x: float
    y: float
    width: float
    height: float


@dataclass
class Detection:
    """Represents a person detection in a video frame.
    
    Attributes:
        bbox: Bounding box coordinates
        confidence: Detection confidence score [0, 1]
        class_id: Object class identifier (0 for person in YOLOv8)
    """
    bbox: BoundingBox
    confidence: float
    class_id: int


class TrackState(Enum):
    """Enumeration of possible track states.
    
    Values:
        ACTIVE: Track is currently being detected
        LOST: Track temporarily lost but within max_age threshold
        REMOVED: Track permanently removed (exceeded max_age)
    """
    ACTIVE = "active"
    LOST = "lost"
    REMOVED = "removed"


@dataclass
class Track:
    """Represents a tracked person across video frames.
    
    Attributes:
        track_id: Unique identifier for this track
        bbox: Current bounding box position
        frame_number: Frame number of last detection
        age: Number of frames since last detection
        state: Current track state (ACTIVE, LOST, or REMOVED)
    """
    track_id: int
    bbox: BoundingBox
    frame_number: int
    age: int
    state: TrackState


class ZoneType(Enum):
    """Enumeration of zone types.
    
    Values:
        GENERAL: Standard store zone (e.g., cosmetics, skincare)
        BILLING_QUEUE: Checkout/billing queue area
    """
    GENERAL = "general"
    BILLING_QUEUE = "billing_queue"


@dataclass
class Point:
    """Represents a 2D point in pixel coordinates.
    
    Attributes:
        x: X-coordinate (pixels)
        y: Y-coordinate (pixels)
    """
    x: float
    y: float


@dataclass
class Zone:
    """Represents a defined spatial region within the store.
    
    Attributes:
        zone_id: Unique identifier for this zone
        zone_name: Human-readable zone name (e.g., "Cosmetics Section")
        polygon: List of points defining the zone boundary
        zone_type: Type of zone (GENERAL or BILLING_QUEUE)
    """
    zone_id: str
    zone_name: str
    polygon: List[Point]
    zone_type: ZoneType


class EventType(Enum):
    """Enumeration of event types generated by the system.
    
    Values:
        ENTRY: Person enters the store
        EXIT: Person exits the store
        ZONE_ENTER: Person enters a defined zone
        ZONE_EXIT: Person exits a defined zone
        ZONE_DWELL: Person dwells in a zone for extended period
        BILLING_QUEUE_JOIN: Person joins the billing queue
        BILLING_QUEUE_ABANDON: Person abandons the billing queue
        REENTRY: Person re-enters after previous exit
    """
    ENTRY = "ENTRY"
    EXIT = "EXIT"
    ZONE_ENTER = "ZONE_ENTER"
    ZONE_EXIT = "ZONE_EXIT"
    ZONE_DWELL = "ZONE_DWELL"
    BILLING_QUEUE_JOIN = "BILLING_QUEUE_JOIN"
    BILLING_QUEUE_ABANDON = "BILLING_QUEUE_ABANDON"
    REENTRY = "REENTRY"


@dataclass
class Event:
    """Represents a structured event generated from tracking data.
    
    All events contain base fields (event_id, event_type, timestamp, store_id, track_id)
    plus event-specific metadata stored in the metadata dictionary.
    
    Attributes:
        event_id: Unique identifier for this event (UUID)
        event_type: Type of event (ENTRY, EXIT, ZONE_ENTER, etc.)
        timestamp: Event timestamp in ISO 8601 format
        store_id: Identifier of the store where event occurred
        track_id: Identifier of the tracked person
        metadata: Event-specific fields (e.g., zone_id, dwell_duration_seconds)
    """
    event_id: str
    event_type: EventType
    timestamp: datetime
    store_id: str
    track_id: int
    metadata: Dict[str, Any]
