"""Core data models for Store Intelligence Platform.

This module defines the fundamental data structures used throughout the system
for representing video frames, detections, tracks, zones, and events.
"""

from dataclasses import dataclass
from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional, Tuple

import numpy as np
from pydantic import BaseModel, Field


@dataclass
class Frame:
    """Represents a single video frame with metadata.
    
    Attributes:
        frame_number: Sequential frame number (0-indexed)
        timestamp: Time in seconds from video start
        image: Frame image data in HxWx3 BGR format (OpenCV format)
        resolution: Frame dimensions as (width, height) tuple
    """
    frame_number: int
    timestamp: float
    image: np.ndarray
    resolution: Tuple[int, int]


@dataclass
class BoundingBox:
    """Represents a rectangular bounding box.
    
    Attributes:
        x: X-coordinate of top-left corner (pixels)
        y: Y-coordinate of top-left corner (pixels)
        width: Box width (pixels)
        height: Box height (pixels)
    """
    x: float
    y: float
    width: float
    height: float


@dataclass
class Detection:
    """Represents a person detection in a video frame.
    
    Attributes:
        bbox: Bounding box coordinates
        confidence: Detection confidence score [0, 1]
        class_id: Object class identifier (0 for person in YOLOv8)
    """
    bbox: BoundingBox
    confidence: float
    class_id: int


class TrackState(Enum):
    """Enumeration of possible track states.
    
    Values:
        ACTIVE: Track is currently being detected
        LOST: Track temporarily lost but within max_age threshold
        REMOVED: Track permanently removed (exceeded max_age)
    """
    ACTIVE = "active"
    LOST = "lost"
    REMOVED = "removed"


@dataclass
class Track:
    """Represents a tracked person across video frames.
    
    Attributes:
        track_id: Unique identifier for this track
        bbox: Current bounding box position
        frame_number: Frame number of last detection
        age: Number of frames since last detection
        state: Current track state (ACTIVE, LOST, or REMOVED)
    """
    track_id: int
    bbox: BoundingBox
    frame_number: int
    age: int
    state: TrackState


class ZoneType(Enum):
    """Enumeration of zone types.
    
    Values:
        GENERAL: Standard store zone (e.g., cosmetics, skincare)
        BILLING_QUEUE: Checkout/billing queue area
    """
    GENERAL = "general"
    BILLING_QUEUE = "billing_queue"


@dataclass
class Point:
    """Represents a 2D point in pixel coordinates.
    
    Attributes:
        x: X-coordinate (pixels)
        y: Y-coordinate (pixels)
    """
    x: float
    y: float


@dataclass
class Zone:
    """Represents a defined spatial region within the store.
    
    Attributes:
        zone_id: Unique identifier for this zone
        zone_name: Human-readable zone name (e.g., "Cosmetics Section")
        polygon: List of points defining the zone boundary
        zone_type: Type of zone (GENERAL or BILLING_QUEUE)
    """
    zone_id: str
    zone_name: str
    polygon: List[Point]
    zone_type: ZoneType


class EventType(Enum):
    """Enumeration of event types generated by the system.
    
    Values:
        ENTRY: Person enters the store
        EXIT: Person exits the store
        ZONE_ENTER: Person enters a defined zone
        ZONE_EXIT: Person exits a defined zone
        ZONE_DWELL: Person dwells in a zone for extended period
        BILLING_QUEUE_JOIN: Person joins the billing queue
        BILLING_QUEUE_ABANDON: Person abandons the billing queue
        REENTRY: Person re-enters after previous exit
    """
    ENTRY = "ENTRY"
    EXIT = "EXIT"
    ZONE_ENTER = "ZONE_ENTER"
    ZONE_EXIT = "ZONE_EXIT"
    ZONE_DWELL = "ZONE_DWELL"
    BILLING_QUEUE_JOIN = "BILLING_QUEUE_JOIN"
    BILLING_QUEUE_ABANDON = "BILLING_QUEUE_ABANDON"
    REENTRY = "REENTRY"


@dataclass
class Event:
    """Represents a structured event generated from tracking data.
    
    All events contain base fields (event_id, event_type, timestamp, store_id, track_id)
    plus event-specific metadata stored in the metadata dictionary.
    
    Attributes:
        event_id: Unique identifier for this event (UUID)
        event_type: Type of event (ENTRY, EXIT, ZONE_ENTER, etc.)
        timestamp: Event timestamp in ISO 8601 format
        store_id: Identifier of the store where event occurred
        track_id: Identifier of the tracked person
        metadata: Event-specific fields (e.g., zone_id, dwell_duration_seconds)
    """
    event_id: str
    event_type: EventType
    timestamp: datetime
    store_id: str
    track_id: int
    metadata: Dict[str, Any]


# ============================================================================
# Pydantic Models for API Request/Response
# ============================================================================

class IngestResponse(BaseModel):
    """Response model for event ingestion endpoint.
    
    Attributes:
        success: Whether the ingestion was successful
        events_processed: Number of events successfully processed
        errors: List of error messages (empty if all succeeded)
    """
    success: bool = Field(..., description="Whether the ingestion was successful")
    events_processed: int = Field(..., ge=0, description="Number of events successfully processed")
    errors: List[str] = Field(default_factory=list, description="List of error messages")


class TimeRange(BaseModel):
    """Time range for filtering metrics.
    
    Attributes:
        start: Start timestamp in ISO 8601 format
        end: End timestamp in ISO 8601 format
    """
    start: datetime = Field(..., description="Start timestamp")
    end: datetime = Field(..., description="End timestamp")


class StoreMetrics(BaseModel):
    """Aggregated metrics for a store.
    
    Attributes:
        store_id: Store identifier
        total_entries: Total number of entry events
        total_exits: Total number of exit events
        current_occupancy: Current number of people in store (entries - exits)
        average_visit_duration_seconds: Average time spent in store
        time_range: Time range for which metrics were calculated
    """
    store_id: str = Field(..., description="Store identifier")
    total_entries: int = Field(..., ge=0, description="Total number of entry events")
    total_exits: int = Field(..., ge=0, description="Total number of exit events")
    current_occupancy: int = Field(..., description="Current occupancy (entries - exits)")
    average_visit_duration_seconds: float = Field(..., ge=0, description="Average visit duration")
    time_range: Optional[TimeRange] = Field(None, description="Time range for metrics")


class FunnelStage(BaseModel):
    """Single stage in the conversion funnel.
    
    Attributes:
        stage: Stage name (entries, zone_visits, billing_queue_joins, completed_purchases)
        count: Number of customers at this stage
        conversion_rate: Conversion rate from previous stage (1.0 for first stage)
    """
    stage: str = Field(..., description="Stage name")
    count: int = Field(..., ge=0, description="Number of customers at this stage")
    conversion_rate: float = Field(..., ge=0, le=1, description="Conversion rate from previous stage")


class ConversionFunnel(BaseModel):
    """Customer journey conversion funnel.
    
    Attributes:
        store_id: Store identifier
        stages: List of funnel stages with counts and conversion rates
        zone_id: Optional zone filter applied
    """
    store_id: str = Field(..., description="Store identifier")
    stages: List[FunnelStage] = Field(..., description="Funnel stages")
    zone_id: Optional[str] = Field(None, description="Zone filter (if applied)")


class GridDimensions(BaseModel):
    """Dimensions of the heatmap grid.
    
    Attributes:
        width: Number of grid cells horizontally
        height: Number of grid cells vertically
    """
    width: int = Field(..., gt=0, description="Grid width in cells")
    height: int = Field(..., gt=0, description="Grid height in cells")


class Heatmap(BaseModel):
    """Spatial density heatmap of customer movement.
    
    Attributes:
        store_id: Store identifier
        resolution: Grid cell size in pixels
        grid: Grid dimensions
        density: 2D array of normalized density values [0, 1]
    """
    store_id: str = Field(..., description="Store identifier")
    resolution: int = Field(..., gt=0, description="Grid cell size in pixels")
    grid: GridDimensions = Field(..., description="Grid dimensions")
    density: List[List[float]] = Field(..., description="2D density array normalized to [0, 1]")


class AnomalyMetrics(BaseModel):
    """Metrics associated with an anomaly.
    
    Attributes:
        baseline: Expected baseline value
        observed: Observed value that triggered anomaly
        threshold: Threshold value for anomaly detection
    """
    baseline: float = Field(..., description="Expected baseline value")
    observed: float = Field(..., description="Observed value")
    threshold: float = Field(..., description="Anomaly detection threshold")


class Anomaly(BaseModel):
    """Detected anomaly in store metrics.
    
    Attributes:
        type: Anomaly type (sudden_crowd_surge, high_queue_abandonment, etc.)
        severity: Severity level (low, medium, high)
        timestamp: When the anomaly was detected
        description: Human-readable description
        metrics: Associated metrics (baseline, observed, threshold)
    """
    type: str = Field(..., description="Anomaly type")
    severity: str = Field(..., pattern="^(low|medium|high)$", description="Severity level")
    timestamp: datetime = Field(..., description="Detection timestamp")
    description: str = Field(..., description="Human-readable description")
    metrics: AnomalyMetrics = Field(..., description="Associated metrics")


class HealthCheck(BaseModel):
    """Individual health check result.
    
    Attributes:
        name: Check name (e.g., 'database')
        status: Check status ('ok', 'degraded', 'failed')
    """
    name: str = Field(..., description="Check name")
    status: str = Field(..., pattern="^(ok|degraded|failed)$", description="Check status")


class HealthStatus(BaseModel):
    """System health status.
    
    Attributes:
        status: Overall system status (healthy, degraded, unhealthy)
        checks: Individual health check results
        response_time_ms: Health check response time in milliseconds
        timestamp: When the health check was performed
    """
    status: str = Field(..., pattern="^(healthy|degraded|unhealthy)$", description="Overall status")
    checks: Dict[str, str] = Field(..., description="Individual check results")
    response_time_ms: float = Field(..., ge=0, description="Response time in milliseconds")
    timestamp: datetime = Field(..., description="Health check timestamp")
